/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 Component Pack 1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Bootloadable_1.h>
#include <UART_1.h>
#include <UART_1_SPI_UART.h>
#include <UART_1_PINS.h>
#include <UART_1_SPI_UART_PVT.h>
#include <UART_1_PVT.h>
#include <UART_1_BOOT.h>
#include <tinyprintf_1_printf.h>
#include <Clock_1.h>
#include <isr.h>
#include <Timer.h>
#include <ISRUART.h>
#include <SignalGenerator.h>
#include <Clock_2.h>
#include <L_Servo.h>
#include <L_Servo_aliases.h>
#include <R_Servo.h>
#include <R_Servo_aliases.h>
#include <Servo_isr.h>
#include <GimbalP.h>
#include <GimbalP_aliases.h>
#include <GimbalT.h>
#include <GimbalT_aliases.h>
#include <SignalSel.h>
#include <InputValue.h>
#include <SPI_1.h>
#include <SPI_1_SPI_UART.h>
#include <SPI_1_PINS.h>
#include <SPI_1_SPI_UART_PVT.h>
#include <SPI_1_PVT.h>
#include <SPI_1_BOOT.h>
#include <UART_1_SCBCLK.h>
#include <UART_1_tx.h>
#include <UART_1_tx_aliases.h>
#include <UART_1_rx.h>
#include <UART_1_rx_aliases.h>
#include <SPI_1_SCBCLK.h>
#include <SPI_1_ss_s.h>
#include <SPI_1_ss_s_aliases.h>
#include <SPI_1_miso_s.h>
#include <SPI_1_miso_s_aliases.h>
#include <SPI_1_sclk_s.h>
#include <SPI_1_sclk_s_aliases.h>
#include <SPI_1_mosi_s.h>
#include <SPI_1_mosi_s_aliases.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

