/*******************************************************************************
 * File Name: project.h
 * cydsfit No Version Information Found
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Bootloadable_1.h>
#include <tinyprintf_1_printf.h>
#include <UART.h>
#include <UART_SPI_UART.h>
#include <UART_PINS.h>
#include <UART_SPI_UART_PVT.h>
#include <UART_PVT.h>
#include <SPIM.h>
#include <SPIM_PVT.h>
#include <LED.h>
#include <LED_aliases.h>
#include <SW.h>
#include <SW_aliases.h>
#include <MISO.h>
#include <MISO_aliases.h>
#include <MOSI.h>
#include <MOSI_aliases.h>
#include <SCLK.h>
#include <SCLK_aliases.h>
#include <WIZ_SS.h>
#include <WIZ_SS_aliases.h>
#include <WIZ_INT.h>
#include <WIZ_INT_aliases.h>
#include <WIZ_RST.h>
#include <WIZ_RST_aliases.h>
#include <WIZ_RDY.h>
#include <WIZ_RDY_aliases.h>
#include <UART_tx.h>
#include <UART_tx_aliases.h>
#include <UART_rx.h>
#include <UART_rx_aliases.h>
#include <SPIM_IntClock.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

